# fly.toml app configuration file generated for sangha-calendar on 2026-04-23T16:54:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sangha-calendar'
primary_region = 'sjc'

[build]

[env]
  DB_PATH = '/data/sangha.db'
  PORT = '8080'

[[mounts]]
  source = 'sangha_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
